# Generated by Django 4.1 on 2022-08-27 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('description', models.CharField(db_column='tx_description', max_length=200)),
                ('value', models.FloatField(db_column='nb_value', default=0)),
                ('type', models.CharField(choices=[('DE', 'Debit'), ('CR', 'Credit')], db_column='tx_type', default='DE', max_length=3)),
                ('expiration_day', models.IntegerField(db_column='nb_expiration_day')),
                ('installments', models.IntegerField(blank=True, db_column='nb_installments', default=0, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransactionsInstallments',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('duedate', models.DateField(db_column='dt_duedate')),
                ('payday', models.DateField(db_column='dt_payday', null=True)),
                ('transaction', models.ForeignKey(db_column='id_transaction', on_delete=django.db.models.deletion.CASCADE, to='transaction.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'transaction_installments',
                'managed': True,
            },
        ),
    ]
