# Generated by Django 4.1 on 2022-08-29 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(db_column='id', primary_key=True, serialize=False)),
                ('active', models.BooleanField(choices=[('True', 'Active'), ('False', 'Inactive')], db_column='cs_active', default='True')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('update_at', models.DateTimeField(auto_now=True, db_column='update_at')),
                ('name', models.CharField(db_column='tx_name', max_length=254)),
                ('email', models.EmailField(db_column='tx_email', max_length=254)),
                ('password', models.CharField(db_column='tx_password', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='transactionsinstallments',
            name='user',
        ),
        migrations.AddField(
            model_name='transaction',
            name='active',
            field=models.BooleanField(choices=[('True', 'Active'), ('False', 'Inactive')], db_column='cs_active', default='True'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='update_at',
            field=models.DateTimeField(auto_now=True, db_column='update_at'),
        ),
        migrations.AddField(
            model_name='transactionsinstallments',
            name='active',
            field=models.BooleanField(choices=[('True', 'Active'), ('False', 'Inactive')], db_column='cs_active', default='True'),
        ),
        migrations.AddField(
            model_name='transactionsinstallments',
            name='update_at',
            field=models.DateTimeField(auto_now=True, db_column='update_at'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(db_column='id_user', on_delete=django.db.models.deletion.DO_NOTHING, to='transaction.user'),
        ),
    ]
