# Generated by Django 4.2.1 on 2023-07-10 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_creditcard_transactionportion_observation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='flag',
            field=models.CharField(choices=[('NC', 'No Card'), ('AL', 'Alelo'), ('AM', 'American Express'), ('EL', 'Elo'), ('HC', 'Hipercard'), ('MA', 'Maestro'), ('MC', 'Mastercard'), ('SO', 'Sodexo'), ('VI', 'Visa'), ('FL', 'Flash')], db_column='tx_flag', default='NC', max_length=2, verbose_name='Flag'),
        ),
    ]
